# -*- coding: utf-8 -*-
"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://wiki.ryzom.com
  name = ryzom

Please do not commit this to the Git repository!
"""
from __future__ import absolute_import, division, unicode_literals

from pywikibot import family
from pywikibot.tools import deprecated


class Family(family.Family):  # noqa: D101

    name = 'ryzom'
    langs = {
        'en': 'en.wiki.ryzom.com',
        'de': 'de.wiki.ryzom.com',
        'es': 'es.wiki.ryzom.com',
        'fr': 'fr.wiki.ryzom.com',
        'ru': 'ru.wiki.ryzom.com',
    }

    def scriptpath(self, code):
        return {
            'en': '/w',
            'de': '/w',
            'es': '/w',
            'fr': '/w',
            'ru': '/w',
        }[code]

    @deprecated('APISite.version()', since='20141225')
    def version(self, code):
        return {
            'en': '1.29.1',
            'de': '1.29.1',
            'es': '1.29.1',
            'fr': '1.29.1',
            'ru': '1.29.1',
        }[code]

    def protocol(self, code):
        return {
            'en': 'https',
            'de': 'https',
            'es': 'https',
            'fr': 'https',
            'ru': 'https',
        }[code]
